version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: printplatform_db
    environment:
      POSTGRES_USER: printplatform_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: printplatform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: